publisher_forward_position_controller:
  ros__parameters:

    controller_name: "forward_position_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2"]
    pos1: [0.0, 0.4, 0.1]
    pos2: [0.4, 0.0, 0.1]
    